services:
  qr-payment-server:
    container_name: qr-payment-server
    build:
      context: .
    volumes:
      - ./src:/go/src
    tty: true
    stdin_open: true
    env_file:
      - server.env
      - db.env
    command: sh -c "sleep 5 && go build && go run qr-payment-server"
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql
    container_name: qr-payment-db
    restart: always
    env_file:
      - db.env
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db: